version: "3"
services:
  ad-rotator:
    image: ad-rotator:latest
    command:
     - --config=/opt/configs/config.compose.toml
    environment:
      - ADR_STORAGE_DSN=postgres://ad-rotator:ad-rotator@db:5432/ad-rotator?sslmode=disable
    volumes:
      - ${ADR_CONFIG_PATH:-../configs}:/opt/configs
    ports:
      - 50051:50051
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ${ADR_DB_PATH:-/tmp/ad-rotator/data/pg}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ad-rotator}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ad-rotator}
      - POSTGRES_DB=${POSTGRES_DB:-ad-rotator}
  zk:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    expose:
      - 2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  kafka:
    hostname: kafka
    image: wurstmeister/kafka:latest
    expose:
      - 9092
      - 19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:19092,INSIDE://:9092
      KAFKA_LISTENERS: OUTSIDE://:19092,INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zk
