language: go

go:
  - "1.15"

os:
  - linux

git:
  depth: 1
  quiet: true
  submodules: false

notifications:
  email: false

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"

before_install:
  - echo "current branch is ${BRANCH}"
  - ls -lA
#  - ls ${BRANCH} && cd ${BRANCH}

stages:
  - name: Tests

jobs:
  include:
    - stage: "Tests"
      name: "go get"
      install: echo "skip"
      script: cd /tmp && go get "github.com/${TRAVIS_REPO_SLUG}/@${BRANCH}"

    - stage: "Tests"
      name: "Linters"
      install: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      script: golangci-lint run ./...

    - stage: "Tests"
      name: "Unit tests"
      install: go mod download
      script: go test -v -count=1 -race -gcflags=-l -timeout=30s ./...
