// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: api/user_group.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserGroup) Reset() {
	*x = UserGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroup) ProtoMessage() {}

func (x *UserGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroup.ProtoReflect.Descriptor instead.
func (*UserGroup) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{0}
}

func (x *UserGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AllUGsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllUGsRequest) Reset() {
	*x = AllUGsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllUGsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUGsRequest) ProtoMessage() {}

func (x *AllUGsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUGsRequest.ProtoReflect.Descriptor instead.
func (*AllUGsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{1}
}

type AllUGsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ugs []*UserGroup `protobuf:"bytes,1,rep,name=ugs,proto3" json:"ugs,omitempty"`
}

func (x *AllUGsResult) Reset() {
	*x = AllUGsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllUGsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUGsResult) ProtoMessage() {}

func (x *AllUGsResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUGsResult.ProtoReflect.Descriptor instead.
func (*AllUGsResult) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{2}
}

func (x *AllUGsResult) GetUgs() []*UserGroup {
	if x != nil {
		return x.Ugs
	}
	return nil
}

type CreateUGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ug *CreateUGRequest_NewUserGroup `protobuf:"bytes,1,opt,name=ug,proto3" json:"ug,omitempty"`
}

func (x *CreateUGRequest) Reset() {
	*x = CreateUGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUGRequest) ProtoMessage() {}

func (x *CreateUGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUGRequest.ProtoReflect.Descriptor instead.
func (*CreateUGRequest) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUGRequest) GetUg() *CreateUGRequest_NewUserGroup {
	if x != nil {
		return x.Ug
	}
	return nil
}

type CreateUGResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ug *UserGroup `protobuf:"bytes,1,opt,name=ug,proto3" json:"ug,omitempty"`
}

func (x *CreateUGResult) Reset() {
	*x = CreateUGResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUGResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUGResult) ProtoMessage() {}

func (x *CreateUGResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUGResult.ProtoReflect.Descriptor instead.
func (*CreateUGResult) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUGResult) GetUg() *UserGroup {
	if x != nil {
		return x.Ug
	}
	return nil
}

type UpdateUGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ug *UserGroup `protobuf:"bytes,1,opt,name=ug,proto3" json:"ug,omitempty"`
}

func (x *UpdateUGRequest) Reset() {
	*x = UpdateUGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUGRequest) ProtoMessage() {}

func (x *UpdateUGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUGRequest.ProtoReflect.Descriptor instead.
func (*UpdateUGRequest) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUGRequest) GetUg() *UserGroup {
	if x != nil {
		return x.Ug
	}
	return nil
}

type UpdateUGResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ug *UserGroup `protobuf:"bytes,1,opt,name=ug,proto3" json:"ug,omitempty"`
}

func (x *UpdateUGResult) Reset() {
	*x = UpdateUGResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUGResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUGResult) ProtoMessage() {}

func (x *UpdateUGResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUGResult.ProtoReflect.Descriptor instead.
func (*UpdateUGResult) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUGResult) GetUg() *UserGroup {
	if x != nil {
		return x.Ug
	}
	return nil
}

type DeleteUGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUGRequest) Reset() {
	*x = DeleteUGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUGRequest) ProtoMessage() {}

func (x *DeleteUGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUGRequest.ProtoReflect.Descriptor instead.
func (*DeleteUGRequest) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUGRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUGResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUGResult) Reset() {
	*x = DeleteUGResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUGResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUGResult) ProtoMessage() {}

func (x *DeleteUGResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUGResult.ProtoReflect.Descriptor instead.
func (*DeleteUGResult) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{8}
}

type CreateUGRequest_NewUserGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateUGRequest_NewUserGroup) Reset() {
	*x = CreateUGRequest_NewUserGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_group_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUGRequest_NewUserGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUGRequest_NewUserGroup) ProtoMessage() {}

func (x *CreateUGRequest_NewUserGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_group_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUGRequest_NewUserGroup.ProtoReflect.Descriptor instead.
func (*CreateUGRequest_NewUserGroup) Descriptor() ([]byte, []int) {
	return file_api_user_group_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateUGRequest_NewUserGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_user_group_proto protoreflect.FileDescriptor

var file_api_user_group_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x2f, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0f, 0x0a, 0x0d,
	0x41, 0x6c, 0x6c, 0x55, 0x47, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a,
	0x0c, 0x41, 0x6c, 0x6c, 0x55, 0x47, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a,
	0x03, 0x75, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x03, 0x75, 0x67, 0x73, 0x22,
	0x68, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x31, 0x0a, 0x02, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x02, 0x75, 0x67, 0x1a, 0x22, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x02, 0x75,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x02, 0x75, 0x67, 0x22, 0x31, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x02, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x02, 0x75, 0x67, 0x22, 0x30,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x1e, 0x0a, 0x02, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x02, 0x75, 0x67,
	0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x47, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x83, 0x02, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x6c, 0x55, 0x47, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6c, 0x6c,
	0x55, 0x47, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x55, 0x47, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x47, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x47, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x47, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_user_group_proto_rawDescOnce sync.Once
	file_api_user_group_proto_rawDescData = file_api_user_group_proto_rawDesc
)

func file_api_user_group_proto_rawDescGZIP() []byte {
	file_api_user_group_proto_rawDescOnce.Do(func() {
		file_api_user_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_group_proto_rawDescData)
	})
	return file_api_user_group_proto_rawDescData
}

var file_api_user_group_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_user_group_proto_goTypes = []interface{}{
	(*UserGroup)(nil),                    // 0: api.UserGroup
	(*AllUGsRequest)(nil),                // 1: api.AllUGsRequest
	(*AllUGsResult)(nil),                 // 2: api.AllUGsResult
	(*CreateUGRequest)(nil),              // 3: api.CreateUGRequest
	(*CreateUGResult)(nil),               // 4: api.CreateUGResult
	(*UpdateUGRequest)(nil),              // 5: api.UpdateUGRequest
	(*UpdateUGResult)(nil),               // 6: api.UpdateUGResult
	(*DeleteUGRequest)(nil),              // 7: api.DeleteUGRequest
	(*DeleteUGResult)(nil),               // 8: api.DeleteUGResult
	(*CreateUGRequest_NewUserGroup)(nil), // 9: api.CreateUGRequest.NewUserGroup
}
var file_api_user_group_proto_depIdxs = []int32{
	0, // 0: api.AllUGsResult.ugs:type_name -> api.UserGroup
	9, // 1: api.CreateUGRequest.ug:type_name -> api.CreateUGRequest.NewUserGroup
	0, // 2: api.CreateUGResult.ug:type_name -> api.UserGroup
	0, // 3: api.UpdateUGRequest.ug:type_name -> api.UserGroup
	0, // 4: api.UpdateUGResult.ug:type_name -> api.UserGroup
	1, // 5: api.UserGroups.UserGroups:input_type -> api.AllUGsRequest
	3, // 6: api.UserGroups.CreateUserGroup:input_type -> api.CreateUGRequest
	5, // 7: api.UserGroups.UpdateUserGroup:input_type -> api.UpdateUGRequest
	7, // 8: api.UserGroups.DeleteUserGroup:input_type -> api.DeleteUGRequest
	2, // 9: api.UserGroups.UserGroups:output_type -> api.AllUGsResult
	4, // 10: api.UserGroups.CreateUserGroup:output_type -> api.CreateUGResult
	6, // 11: api.UserGroups.UpdateUserGroup:output_type -> api.UpdateUGResult
	8, // 12: api.UserGroups.DeleteUserGroup:output_type -> api.DeleteUGResult
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_user_group_proto_init() }
func file_api_user_group_proto_init() {
	if File_api_user_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_user_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllUGsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllUGsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUGResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUGResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUGResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_group_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUGRequest_NewUserGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_group_proto_goTypes,
		DependencyIndexes: file_api_user_group_proto_depIdxs,
		MessageInfos:      file_api_user_group_proto_msgTypes,
	}.Build()
	File_api_user_group_proto = out.File
	file_api_user_group_proto_rawDesc = nil
	file_api_user_group_proto_goTypes = nil
	file_api_user_group_proto_depIdxs = nil
}
