[api]
listen = '0.0.0.0:50051'

[logger]
backend = 'logrus'
file = ''
level = 'DEBUG'

[storage]
dsn = 'postgres://ad-rotator:ad-rotator@db:5432/ad-rotator?sslmode=disable'
max_conn = 10
max_idle_conn = 30
retry = 20
retry_interval = '500ms'
